#!/usr/bin/env python3
"""
replicate.py — Entry-point for reproducing all results in:

    "Hyperparameters Over Architecture: A Controlled Comparison of
     Neural Networks for Aggregate Loss Reserving"

Usage
-----
    # Verify paper figures from pre-computed results (~30 seconds)
    python replicate.py

    # Full replication using CAS public data (~5 hours on NVIDIA GB10 GPU)
    python replicate.py --cas

    # Run a specific step only
    python replicate.py --cas --step phase1
    python replicate.py --step figures

    # Force regeneration of figures even if they already exist
    python replicate.py --force
"""

from __future__ import annotations

import argparse
import json
import math
import os
import platform
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROJECT_DIR = Path(__file__).parent.resolve()
RESULTS_DIR = Path(os.environ.get("DEEPTRIANGLE_RESULTS", str(PROJECT_DIR / "results")))
FIGURES_DIR = RESULTS_DIR / "figures"

PAPER_TITLE = (
    "Hyperparameters Over Architecture: A Controlled Comparison of\n"
    "Neural Networks for Aggregate Loss Reserving"
)

EXPECTED_FIGURES = [
    "architecture_compare.pdf",
    "mape_boxplot.pdf",
    "attention_bimodal.pdf",
    "rf_importance.pdf",
    "partial_dependence.png",
    "temporal_robustness.pdf",
    "tab1_results.tex",
]

# Hand-crafted figures shipped with the repo; not regenerated by any script.
# Preserved during --force clears.
STATIC_FIGURES = {"architecture_compare.pdf"}

REQUIRED_PACKAGES = [
    "torch", "pandas", "numpy", "sklearn", "matplotlib", "scipy",
]

# Additional packages needed only for CAS (full training) mode
CAS_EXTRA_PACKAGES = [
    "chainladder",
]

# Subdirectories expected by verify mode
REQUIRED_RESULT_DIRS = [
    "phase1",
    "phase2/workers_compensation",
    "phase2/workers_compensation/multiseed",
    "phase2/private_passenger_auto",
    "phase2/private_passenger_auto/multiseed",
    "temporal",
]


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

class StepResult:
    """Tracks the outcome of a single pipeline step."""

    def __init__(self, name: str, success: bool, elapsed: float, message: str = ""):
        self.name = name
        self.success = success
        self.elapsed = elapsed
        self.message = message


def print_banner() -> None:
    """Print paper title banner."""
    width = 72
    print()
    print("=" * width)
    print(PAPER_TITLE.center(width))
    print("=" * width)
    print("Replication Script".center(width))
    print("=" * width)
    print()


def format_time(seconds: float) -> str:
    """Human-readable elapsed time."""
    if seconds < 60:
        return f"{seconds:.1f}s"
    elif seconds < 3600:
        m, s = divmod(seconds, 60)
        return f"{int(m)}m {s:.0f}s"
    else:
        h, remainder = divmod(seconds, 3600)
        m, s = divmod(remainder, 60)
        return f"{int(h)}h {int(m)}m {int(s)}s"


def log_hardware() -> None:
    """Print hardware and environment information."""
    print("Environment")
    print("-" * 40)
    print(f"  Python     : {sys.version.split()[0]}")
    print(f"  Platform   : {platform.platform()}")
    print(f"  CPU        : {platform.processor() or platform.machine()}")

    try:
        import torch
        print(f"  PyTorch    : {torch.__version__}")
        if torch.cuda.is_available():
            print(f"  GPU        : {torch.cuda.get_device_name(0)}")
            print(f"  CUDA       : {torch.version.cuda}")
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            print(f"  GPU        : Apple MPS (Metal)")
        else:
            print(f"  GPU        : None (CPU only)")
    except ImportError:
        print("  PyTorch    : NOT INSTALLED")

    print()


def check_packages() -> bool:
    """Verify that required packages are importable."""
    missing: List[str] = []
    for pkg in REQUIRED_PACKAGES:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)

    if missing:
        print("ERROR: Missing required packages:")
        for pkg in missing:
            print(f"  - {pkg}")
        print(f"\nInstall with:  pip install -r requirements.txt")
        return False
    return True


def check_results_dirs() -> bool:
    """Verify that expected source results subdirectories exist."""
    missing: List[str] = []
    for subdir in REQUIRED_RESULT_DIRS:
        if not (RESULTS_DIR / subdir).is_dir():
            missing.append(subdir)

    if missing:
        print("ERROR: Missing results subdirectories:")
        for d in missing:
            print(f"  - results/{d}")
        print("\nPre-computed source results are required for --verify mode.")
        print("Generated figures are intentionally not shipped; run replicate.py to create them.")
        print("Use --cas to run the full pipeline from scratch.")
        return False
    return True


DEFAULT_TIMEOUT = 7200  # 2 hours per step
LONG_TIMEOUT = 43200    # 12 hours for training-heavy steps (Phase 1)



def _mean_std(values: List[float]) -> Tuple[float, float]:
    if not values:
        return float("nan"), float("nan")
    mean = sum(values) / len(values)
    if len(values) == 1:
        return mean, 0.0
    var = sum((v - mean) ** 2 for v in values) / (len(values) - 1)
    return mean, math.sqrt(var)


def _load_json_mapes(pattern: str) -> List[Dict[str, float]]:
    rows: List[Dict[str, float]] = []
    for path in sorted(RESULTS_DIR.glob(pattern)):
        with open(path) as f:
            d = json.load(f)
        mape = d.get("mape")
        rmspe = d.get("rmspe")
        if mape is not None and mape == mape:
            rows.append({"mape": float(mape), "rmspe": float(rmspe) if rmspe is not None else float("nan")})
    return rows


def print_paper_results_summary() -> None:
    """Print the paper-facing table and figure summary."""
    archs = [
        ("gru_baseline", "GRU Baseline"),
        ("gru_attention", "GRU + Attn. (masked)"),
        ("gru_attention_unmasked", "GRU + Attn. (unmasked)"),
    ]
    lobs = [("workers_compensation", "WC"), ("private_passenger_auto", "PPA")]

    print("=" * 80)
    print("PAPER TABLE / FIGURE SUMMARY")
    print("=" * 80)
    print("\nTable 1 source: results/phase1/phase1_summary.csv\n")

    import pandas as pd
    phase1_summary = RESULTS_DIR / "phase1" / "phase1_summary.csv"
    df_phase1 = pd.read_csv(phase1_summary)

    for arch, label in archs:
        for lob, lob_short in lobs:
            subset = df_phase1[(df_phase1["arch"] == arch) & (df_phase1["lob"] == lob)]
            mapes = subset["mape"].astype(float).tolist()
            rmspes = subset["rmspe"].astype(float).tolist()
            m_mape, s_mape = _mean_std(mapes)
            m_rmspe, s_rmspe = _mean_std(rmspes)
            print(
                f"  {label:30s} {lob_short:4s} "
                f"MAPE={m_mape*100:5.2f}% ± {s_mape*100:4.2f}%  "
                f"RMSPE={m_rmspe*100:5.2f}% ± {s_rmspe*100:4.2f}%  "
                f"N={len(subset):3d}"
            )

    ppa_summary = RESULTS_DIR / "phase2" / "private_passenger_auto" / "multiseed" / "phase2_top20_summary.csv"
    if ppa_summary.exists():
        import pandas as pd
        df = pd.read_csv(ppa_summary).sort_values("mean_mape")
        print("\nNative PPA Phase 2 top configurations:")
        for _, row in df.head(5).iterrows():
            std = row.get("std_mape", 0.0)
            print(
                f"  cfg={int(row['config_idx']):3d}  "
                f"mean MAPE={row['mean_mape']*100:5.2f}%  "
                f"std={std*100:5.3f}%  "
                f"lr={row['learning_rate']:.2e}  "
                f"drop={row['dropout_rate']:.3f}  "
                f"gru={int(row['gru_units'])}"
            )

    print("\nGenerated figure/table artifacts:")
    for name in EXPECTED_FIGURES:
        path = FIGURES_DIR / name
        status = "OK" if path.exists() else "MISSING"
        print(f"  [{status:7s}] results/figures/{name}")

def run_script(
    cmd: List[str],
    label: str,
    quiet: bool = False,
    timeout: int = DEFAULT_TIMEOUT,
) -> Tuple[bool, str]:
    """Run a Python script as a subprocess.

    Returns (success, error_message).
    """
    if cmd == ["__paper_summary__"]:
        try:
            print_paper_results_summary()
            return True, ""
        except Exception as e:
            return False, str(e)

    full_cmd = [sys.executable] + cmd
    try:
        if quiet:
            result = subprocess.run(
                full_cmd,
                cwd=str(PROJECT_DIR),
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            if result.returncode != 0:
                return False, result.stderr[-2000:] if result.stderr else "Non-zero exit code"
        else:
            print(f"  $ python {' '.join(cmd)}")
            result = subprocess.run(
                full_cmd,
                cwd=str(PROJECT_DIR),
                timeout=timeout,
            )
            if result.returncode != 0:
                return False, f"Exit code {result.returncode}"
        return True, ""
    except subprocess.TimeoutExpired:
        return False, f"Timed out (>{timeout // 3600}h)"
    except Exception as e:
        return False, str(e)


def run_step(
    step_num: int,
    total_steps: int,
    name: str,
    cmd: List[str],
    quiet: bool = False,
    timeout: int = DEFAULT_TIMEOUT,
) -> StepResult:
    """Run a numbered pipeline step and return its result."""
    print(f"\n[{step_num}/{total_steps}] {name}")
    print("-" * 50)

    t0 = time.time()
    success, error = run_script(cmd, name, quiet=quiet, timeout=timeout)
    elapsed = time.time() - t0

    if success:
        print(f"  Done ({format_time(elapsed)})")
    else:
        print(f"  FAILED ({format_time(elapsed)}): {error}")

    return StepResult(name, success, elapsed, error)


def count_figures() -> int:
    """Count paper-facing figure files in the figures directory."""
    if not FIGURES_DIR.is_dir():
        return 0
    return len(list(FIGURES_DIR.glob("*.pdf"))) + len(list(FIGURES_DIR.glob("*.png")))


def print_summary(results: List[StepResult], total_elapsed: float) -> None:
    """Print final summary of all steps."""
    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)

    failures = [r for r in results if not r.success]
    successes = [r for r in results if r.success]

    for r in results:
        status = "OK" if r.success else "FAIL"
        print(f"  [{status:>4}] {r.name:<40} {format_time(r.elapsed):>8}")

    print("-" * 60)
    print(f"  Steps: {len(successes)}/{len(results)} succeeded")

    n_figs = count_figures()
    if n_figs > 0:
        print(f"  Figures: {n_figs} PDF/PNG files in results/figures/")

    print(f"  Total time: {format_time(total_elapsed)}")

    if failures:
        print(f"\n  FAILURES ({len(failures)}):")
        for r in failures:
            print(f"    - {r.name}: {r.message}")

    print()


# ---------------------------------------------------------------------------
# Pipeline modes
# ---------------------------------------------------------------------------

def run_verify(
    quiet: bool = False,
    force: bool = False,
    step_filter: Optional[str] = None,
) -> None:
    """Verify mode: regenerate figures from pre-computed results."""

    print("Mode: VERIFY (regenerate figures from shipped results)")
    print()

    if not check_packages():
        sys.exit(1)

    if not check_results_dirs():
        sys.exit(1)

    # Define analysis steps: (name, cmd, timeout)
    all_steps: List[Tuple[str, List[str], int]] = [
        ("Analyze paper figures and tables", ["analyze_results.py"], DEFAULT_TIMEOUT),
        ("Generate HP partial-dependence figure", ["analyze_hp_sensitivity.py", "--output", "results/figures"], DEFAULT_TIMEOUT),
        ("Show paper table/figure summary", ["__paper_summary__"], DEFAULT_TIMEOUT),
    ]

    # Filter to a single step if requested
    if step_filter:
        step_map: Dict[str, List[int]] = {
            "figures": [0, 1],
            "analysis": [0, 1, 2],
            "tables": [2],
        }
        indices = step_map.get(step_filter)
        if indices is None:
            valid = ", ".join(step_map.keys())
            print(f"ERROR: Unknown step '{step_filter}' for verify mode.")
            print(f"Valid steps: {valid}")
            sys.exit(1)
        all_steps = [all_steps[i] for i in indices]

    # Optionally clear existing figures (preserving hand-crafted assets)
    if force and FIGURES_DIR.is_dir():
        for f in FIGURES_DIR.glob("*.pdf"):
            if f.name not in STATIC_FIGURES:
                f.unlink()
        for f in FIGURES_DIR.glob("*.png"):
            if f.name not in STATIC_FIGURES:
                f.unlink()
        print("Cleared existing figures.\n")

    results: List[StepResult] = []
    total_steps = len(all_steps)
    t_total = time.time()

    for i, (name, cmd, step_timeout) in enumerate(all_steps, 1):
        result = run_step(i, total_steps, name, cmd, quiet=quiet, timeout=step_timeout)
        results.append(result)

    print_summary(results, time.time() - t_total)


def run_cas(
    quiet: bool = False,
    step_filter: Optional[str] = None,
) -> None:
    """CAS mode: full replication from public data."""

    print("Mode: CAS (full replication from public data)")
    print()

    # CAS data covers AY 1998-2007 (10 dev lags).
    # Following Kuo (2019): train ≤ CY 2005, val CY 2006-2007, test CY 2008.
    os.environ["DEEPTRIANGLE_TRAIN_CUTOFF"] = "2005"
    os.environ["DEEPTRIANGLE_VAL_START"] = "2006"
    os.environ["DEEPTRIANGLE_VAL_END"] = "2007"
    os.environ["DEEPTRIANGLE_TEST_CAL"] = "2008"
    os.environ["DEEPTRIANGLE_TEST_MAX_AY"] = "2007"
    os.environ["DEEPTRIANGLE_AY_MIN"] = "1998"
    print("CAS temporal splits: train ≤ CY 2005, val 2006-2007, test 2008")
    print("This will download CAS data, run all training experiments,")
    print("and regenerate all figures. Estimated time: ~5 hours on an NVIDIA GB10 GPU (DGX Spark) in our measurements.")
    print()

    if not check_packages():
        sys.exit(1)

    # CAS mode needs additional packages
    missing_extra: List[str] = []
    for pkg in CAS_EXTRA_PACKAGES:
        try:
            __import__(pkg)
        except ImportError:
            missing_extra.append(pkg)
    if missing_extra:
        print("ERROR: CAS mode requires additional packages:")
        for pkg in missing_extra:
            print(f"  - {pkg}")
        print(f"\nInstall with:  pip install {' '.join(missing_extra)}")
        sys.exit(1)

    # Define all pipeline steps: (name, cmd, timeout)
    # Training-heavy steps get LONG_TIMEOUT (12h); analysis steps use DEFAULT_TIMEOUT (2h).
    all_steps: List[Tuple[str, List[str], int]] = [
        ("Download & convert CAS data", ["convert_cas_data.py"], DEFAULT_TIMEOUT),
        ("Phase 1: Architecture comparison (300 runs)", ["run_phase1.py"], LONG_TIMEOUT),
        ("Classical benchmarks (Mack CL, ODP, BF)", ["benchmarks.py", "--no-automl"], DEFAULT_TIMEOUT),
        ("Phase 2: HP screening (100 configs)", ["run_phase2_multiseed.py", "--stage", "1"], LONG_TIMEOUT),
        ("Phase 2: Multi-seed validation (top 20)", ["run_phase2_multiseed.py", "--stage", "2"], LONG_TIMEOUT),
        ("Temporal robustness (3 windows)", ["run_temporal.py", "--archs", "gru_baseline"], LONG_TIMEOUT),
        ("Kuo comparison experiments", ["run_kuo_comparison.py"], DEFAULT_TIMEOUT),
        ("Analyze paper figures and tables", ["analyze_results.py"], DEFAULT_TIMEOUT),
        ("Generate HP partial-dependence figure", ["analyze_hp_sensitivity.py", "--output", "results/figures"], DEFAULT_TIMEOUT),
        ("Analyze maturity effects", ["analyze_maturity.py"], DEFAULT_TIMEOUT),
        ("Show paper table/figure summary", ["__paper_summary__"], DEFAULT_TIMEOUT),
    ]

    # Filter to a single step if requested
    if step_filter:
        step_map: Dict[str, List[int]] = {
            "data": [0],
            "phase1": [1],
            "benchmarks": [2],
            "phase2": [3, 4],
            "phase2-screen": [3],
            "phase2-validate": [4],
            "temporal": [5],
            "kuo": [6],
            "figures": [7, 8],
            "analysis": [7, 8, 9, 10],
            "maturity": [9],
            "tables": [10],
        }
        indices = step_map.get(step_filter)
        if indices is None:
            valid = ", ".join(step_map.keys())
            print(f"ERROR: Unknown step '{step_filter}' for --cas mode.")
            print(f"Valid steps: {valid}")
            sys.exit(1)
        all_steps = [all_steps[i] for i in indices]

    results: List[StepResult] = []
    total_steps = len(all_steps)
    t_total = time.time()

    for i, (name, cmd, step_timeout) in enumerate(all_steps, 1):
        result = run_step(i, total_steps, name, cmd, quiet=quiet, timeout=step_timeout)
        results.append(result)

    print_summary(results, time.time() - t_total)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Replicate all results from the paper.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
examples:
  python replicate.py                  # verify figures from pre-computed results
  python replicate.py --cas            # full replication from CAS public data
  python replicate.py --step figures   # regenerate figures only
  python replicate.py --cas --step phase1  # run Phase 1 training only
""",
    )

    parser.add_argument(
        "--cas",
        action="store_true",
        help="Full replication: download CAS data, train all models, generate figures",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        default=True,
        help="Verify mode (default): regenerate figures from shipped results",
    )
    parser.add_argument(
        "--step",
        type=str,
        default=None,
        metavar="STEP",
        help=(
            "Run only a specific step. "
            "Verify: figures, analysis, tables. "
            "CAS: data, phase1, benchmarks, phase2, phase2-screen, phase2-validate, "
            "temporal, kuo, figures, analysis, maturity, tables"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force regeneration even if output files exist (verify mode)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress subprocess output (show progress only)",
    )
    parser.add_argument(
        "--results-dir",
        type=str,
        default=None,
        metavar="DIR",
        help="Output directory for results (default: results/). "
             "Useful for running CAS replication without overwriting existing results.",
    )

    args = parser.parse_args()

    # Set results directory via env var (inherited by all subprocesses)
    if args.results_dir:
        results_path = Path(args.results_dir).resolve()
        os.environ["DEEPTRIANGLE_RESULTS"] = str(results_path)
        # Update module-level vars to match
        global RESULTS_DIR, FIGURES_DIR
        RESULTS_DIR = results_path
        FIGURES_DIR = results_path / "figures"
        print(f"Results directory: {results_path}\n")

    print_banner()
    log_hardware()

    if args.cas:
        run_cas(quiet=args.quiet, step_filter=args.step)
    else:
        run_verify(quiet=args.quiet, force=args.force, step_filter=args.step)


if __name__ == "__main__":
    main()
